alpha_prior:
- 9
- 1
data:
  snv:
    file: merged.tsv.gz
    gamma_prior:
    - - 98
      - 1
      - 1
    - - 25
      - 50
      - 25
    - - 1
      - 1
      - 98
    state_prior:
    - 1
    - 1
    - 1
kappa_prior: 1
num_clusters: '5'
